### ISSUE TITLE
BigCommerce cart research

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#254]
# Description

Make a cart for BigCommerce

**Comment by jonmediajel** [comment]
We can create scripts from the Store Front > Script manager. So that it would not be a manual process to add <script> Tags on console. Because I notice when viewing another page it would refresh the website and we need to redo the manual process again. Create scripts from script manager so that its automated.

![image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/34b0f564-0c05-412b-8da8-89d20e231d81)

**Comment by jonmediajel** [comment]
Done: 
![image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/13f95aeb-387c-4474-a1ac-514cec9e2359)

![image](https://github.com/MediaJel/mediajel-tracker/assets/76018662/c4017300-a46a-4e28-aa2b-29bb5ec9a806)
